### ISSUE TITLE
Zxing Lib

### ISSUE THREAD

**Issue by lucashorn** [geekcom/phpjasper#299]
what is the possibility of adding zxing for QRcode support? The lib added in bin/jasperstarter/jdbc/ 

I use phpjasper but for the current project I need to generate qrcode, needing this lib in the project.

**Comment by Xint0-elab** [comment]
Hi @lucashorn,

I have pull request #311 pending which upgrades JasperStarter to version 3.6.2 which now includes the zxing library.

You can try it out using my fork https://github.com/Xint0-elab/phpjasper.git in your `composer.json` with the branch `dev-Upgrade_to_JasperStarter_3.6.2`:

```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/Xint0-elab/phpjasper.git"
    }
  ],
  "require": {
    "geekcom/phpjasper": "dev-Upgrade_to_JasperStarter_3.6.2"
  }
}
```

**Comment by lucashorn** [comment]
Thanks man, this solved my problems. Including the new ones for "attribute 'textAdjust'" that appeared to me due to version incompatibility

**Comment by lucashorn** [comment]
> Hi @lucashorn,
> 
> I have pull request #311 pending which upgrades JasperStarter to version 3.6.2 which now includes the zxing library.
> 
> You can try it out using my fork https://github.com/Xint0-elab/phpjasper.git in your `composer.json` with the branch `dev-Upgrade_to_JasperStarter_3.6.2`:
> 
> ```json
> {
>   "repositories": [
>     {
>       "type": "vcs",
>       "url": "https://github.com/Xint0-elab/phpjasper.git"
>     }
>   ],
>   "require": {
>     "geekcom/phpjasper": "dev-Upgrade_to_JasperStarter_3.6.2"
>   }
> }
> ```

Thanks man, this solved my problems. Including the new ones for "attribute 'textAdjust'" that appeared to me due to version incompatibility
