### ISSUE TITLE
Add PHP 8 Support

### ISSUE THREAD

**Issue by flavioafa** [geekcom/phpjasper#305]
Hello guys! 

Any plans to make this library PHP 8 compatible?

**Comment by vitormattos** [comment]
Yes!
The plan:
* Fork
* swap your PHP version to 8
* Run unit tests and check what broken
* fix the broken tests
* Run smoke tests
* Create a new PR with subject "Make this library PHP 8 compatible"

**Comment by vitormattos** [comment]
Duplicated by  #271
